### ISSUE TITLE
Altair GraphQL Client has other platform support

### ISSUE THREAD

**Issue by imolorhe** [wp-graphql/docs.wpgraphql.com#13]
Hello,

In the "Exploring with GraphQL" page, you listed Altair GraphQL Client as a chrome extension. It has more binaries for all the desktop platforms and also extension for FireFox too. :)

https://altair.sirmuel.design/

Also those are GraphQL tools, not a GraphiQL tools. GraphiQL is a GraphQL tool of its own.

**Comment by jasonbahl** [comment]
Hey! 

Thanks for clarifying. I didn't realize that Altair didn't use GraphiQL under the hood 🤦‍♂️ 

I'll update this in the docs to clarify.
