### ISSUE TITLE
Relay and node part of docs not working

### ISSUE THREAD

**Issue by proksimacentauri** [wp-graphql/docs.wpgraphql.com#61]
Hi! 

In the docs site the relay spec link/page isnt working. 
I would just like an explanation of what the nodes and edges are used for and how they work. :)

https://docs.wpgraphql.com/guides/relay-spec

**Comment by jasonbahl** [comment]
@Dongerina Hey! Thanks for pointing this out. This has been on my "todo" list for a while and I just had some time to write out some content for this. 

You can see the raw page here: https://github.com/wp-graphql/docs.wpgraphql.com/blob/master/src/content/guides/relay-spec.mdx 

and in its rendered form on the site here: https://docs.wpgraphql.com/guides/relay-spec
